# Generated by Django 5.0 on 2024-03-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_brand_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('out_of_stock', 'Out of Stock'), ('on_sale', 'On Sale'), ('discontinued', 'Discontinued')], default='available', max_length=20),
        ),
    ]
