export const GET_PRODUCT_LIST_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_PRODUCT_LIST_FAIL = 'GET_CATEGORIES_FAIL';

export const GET_PRODUCT_LIST_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_PRODUCT_LIST_CATEGORIES_FAIL = 'GET_CATEGORIES_FAIL';

export const GET_PRODUCT_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_PRODUCT_FAIL = 'GET_CATEGORIES_FAIL';
export const GET_SEARCH_PRODUCT_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_SEARCH_PRODUCT_FAIL = 'GET_CATEGORIES_FAIL';